### ISSUE TITLE
Encountering an error as I attempt to add an object into my IDF file using eplusr

### ISSUE THREAD

**Issue by mdakyen** [hongyuanjia/epluspar#30]
Good sir,
I have been trying to add an object to my IDF file using eplusr, but I kept encountering an error. Below are my codes and the error.
mywork<-(WindowMaterial:Glazing = list(Name = "clear glass 4 mm",
                                      Optical_Data_Type = "SpectralAverage", 
                                      SpectralAverage =0.0039,
                                      Solar_Transmittance_at_Normal_Incidence =0.812 ,
                                      Front_Side_Solar_Reflectance_at_Normal_Incidence =0.076 ,
                                      Back_Side_Solar_Reflectance_at_Normal_Incidence =0.075,
                                      Visible_Transmittance_at_Normal_Incidence =0.893,
                                      Front_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
                                      Back_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
                                      Infrared_Transmittance_at_Normal_Incidence =0,
                                      Front_Side_Infrared_Hemispherical_Emissivity  =0.840,
                                      Back_Side_Infrared_Hemispherical_Emissivity =0.840,
                                      Conductivity = 0.9))
idf$add(mywork)

Error in WindowMaterial:Glazing = list(Name = "clear glass 4 mm", Optical_Data_Type = "SpectralAverage",  : 
  object 'WindowMaterial' not found

**Comment by hongyuanjia** [comment]
This is when you mentioning a class that contains a colon, you have to change the class name to underscore style, i.e. from `WindowMaterial:Glazing` to `WindowMaterial_Glazing`, or quote it `"WindowMaterial:Glazing"`

**Comment by mdakyen** [comment]
Thanks for your response, sir. 
I implemented your recommendation, as follows: 
mywork<-(WindowMaterial_Glazing = list(Name = "clear glass 4 mm",
                                      Optical_Data_Type = "SpectralAverage", 
                                      SpectralAverage =0.0039,
                                      Solar_Transmittance_at_Normal_Incidence =0.812 ,
                                      Front_Side_Solar_Reflectance_at_Normal_Incidence =0.076 ,
                                      Back_Side_Solar_Reflectance_at_Normal_Incidence =0.075,
                                      Visible_Transmittance_at_Normal_Incidence =0.893,
                                      Front_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
                                      Back_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
                                      Infrared_Transmittance_at_Normal_Incidence =0,
                                      Front_Side_Infrared_Hemispherical_Emissivity  =0.840,
                                      Back_Side_Infrared_Hemispherical_Emissivity =0.840,
                                      Conductivity = 0.9))
idf$add(mywork)
However, I still encounted the following error:
Error: Assertion on 'Input' failed: Must be named.

**Comment by hongyuanjia** [comment]
If you are trying to modify or add objects to an `Idf` object, please follow the instruction [here](https://hongyuanjia.github.io/eplusr/articles/eplusr.html#add-new-objects-using-lists-idfadd), i.e. make sure input passed to `Idf$add()` is a list. For your case, you should do:

```r
mywork<- list(WindowMaterial_Glazing = list(Name = "clear glass 4 mm",
    Optical_Data_Type = "SpectralAverage",
    SpectralAverage =0.0039,
    Solar_Transmittance_at_Normal_Incidence =0.812 ,
    Front_Side_Solar_Reflectance_at_Normal_Incidence =0.076 ,
    Back_Side_Solar_Reflectance_at_Normal_Incidence =0.075,
    Visible_Transmittance_at_Normal_Incidence =0.893,
    Front_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
    Back_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
    Infrared_Transmittance_at_Normal_Incidence =0,
    Front_Side_Infrared_Hemispherical_Emissivity =0.840,
    Back_Side_Infrared_Hemispherical_Emissivity =0.840,
    Conductivity = 0.9))

idf$add(mywork)
```

**Comment by mdakyen** [comment]
Followed your suggestions again Sir, but am still faced with the following error:
Error: Invalid field name found:
 #3| Class 'WindowMaterial:Glazing': 'SpectralAverage'.

**Comment by mdakyen** [comment]
Sorry Sir, noticed my mistake. Below is the correct code and its working now.
mywork<-list(WindowMaterial_Glazing = list(Name = "clear glass 4 mm",
                                      Optical_Data_Type = "SpectralAverage",
                                      Thickness =0.0039,
                                      Solar_Transmittance_at_Normal_Incidence =0.812 ,
                                      Front_Side_Solar_Reflectance_at_Normal_Incidence =0.076 ,
                                      Back_Side_Solar_Reflectance_at_Normal_Incidence =0.075,
                                      Visible_Transmittance_at_Normal_Incidence =0.893,
                                      Front_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
                                      Back_Side_Visible_Reflectance_at_Normal_Incidence =0.084,
                                      Infrared_Transmittance_at_Normal_Incidence =0,
                                      Front_Side_Infrared_Hemispherical_Emissivity  =0.840,
                                      Back_Side_Infrared_Hemispherical_Emissivity =0.840,
                                      Conductivity = 0.9))
idf$add(mywork)

Thanks for your swift response, sir.

**Comment by hongyuanjia** [comment]
Great. Good to know it works.
